# Generated by Django 3.1.4 on 2020-12-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201225_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='regno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
