# Generated by Django 3.1.4 on 2020-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_donor_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='photo',
            field=models.ImageField(default=1, upload_to='upload'),
            preserve_default=False,
        ),
    ]
