# Generated by Django 3.1.4 on 2020-12-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201227_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptor',
            name='photo',
            field=models.ImageField(default=5, upload_to='upload/AcceptorImg/'),
            preserve_default=False,
        ),
    ]
