# Generated by Django 3.1.4 on 2020-12-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_acceptor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptor',
            name='regno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
